# Generated by Django 2.2 on 2020-04-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, help_text='Early Access Email User', max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Early Access Phone', max_length=16, null=True, unique=True)),
                ('pod_type', models.IntegerField(choices=[(1, 'CONTAMINATION'), (2, 'SOCIAL'), (3, 'RELIGIOUS'), (4, 'OTHER')], default=1, help_text='Select a Podcast Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
